### FIXME according to the target version
# base image
FROM ros:humble-ros-core-jammy

# Set Ubuntu Codename
ENV UBUNTU_CODENAME jammy && \
  # Set ROS_DISTRO environment
  ROS_DISTRO humble && \
  # force error about debconf
  DEBIAN_FRONTEND noninteractive

# update sources list
RUN apt-get clean && \
  apt-get update && \
  # install AStyle to format C code (NIFs)
  apt-get install -y astyle && \
  # install erlang and elixir
  apt-get install -y erlang-dev elixir

# cleanup
RUN apt-get -qy autoremove

# install hex and rebar
RUN mix local.hex --force && \
  mix local.rebar --force

# check version
RUN env | grep ROS
RUN mix hex.info